---
# vars file for SonarQube

# Packages necessary to install.
apt_packages:
  - python3-pip
  - podman

# Packages necessary to install.
pip_packages:
  - pyyaml
  - kubernetes
  - openshift

# Template name k8s *.yaml.
k8s_templates:
  - sonar-data.yml
  - sonar-extensions.yml
  - sonar-secret.yml
  - sonar-deployment.yml
  - sonar-service.yml

# URL for ACR.
acr_url: rracontainerregistry.azurecr.io

# Tag for container image.
tag_image: casopractico2

# k8s namespace.
k8s_namespace: "sonarqube"

# k8s Deployment yaml vars.
deployment:
  name: sonarqube
  image: {{ acr_url }}/sonarqube:{{ tag_image }}
  replicas: 1
  terminationGracePeriodSeconds: 15
  containers:
    resources:
      cpu: 2200m
      memory: 4096Mi
    limits:
      cpu: 2800m
      memory: 6144Mi
    ports:
      containerPort: 9000
      name: sonarqube
    env:
      username: rrabanedo
      url: jdbc:h2:tcp://127.0.0.1:9092/sonar
      #url: jdbc:postgresql:tcp://{{ tf_webservice_pip }}:5432/sonarqube
  initContainers:
    name: fix-the-volume-permission
    image: busybox
    volumeMounts:
      name: sonar
      mountPath: /opt/sonarqube

# k8s Service yaml vars.
svc:
  name: sonarqube
  ports:
    name: sonar
    port: 1080
    protocol: TCP
    targetPort: 9000
  type: LoadBalancer

# k8s PersistentVolumeClaim yaml vars.
pvc:
  name: sonar
  accessModes: ReadWriteOnce
  storageClassName: default
  storage: 5Gi

# k8s Secrets yaml info.
# Encrypted in Base64: echo -n '1nd3sc1fr4bl3@cp2' | base64
...