---
# vars file for SonarQube

# APT packages necessary to images (SonarQube).
apt_packages:
  - python3-pip
  - podman

# Python necessary packages for k8s.
pip_packages:
  - pyyaml
  - kubernetes
  - openshift

# Template k8s' name *.yaml.
k8s_templates:
  - sonar-data.yml
  - sonar-extensions.yml
  - sonar-secret.yml
  - sonar-deployment.yml
  - sonar-service.yml

# The k8s namespace.
k8s_namespace: "sonarqube"

# The k8s Deployment yaml vars.
deployment:
  name: sonarqube
  image: rracontainerregistry.azurecr.io/sonarqube:casopractico2
  replicas: 1
  terminationGracePeriodSeconds: 15
  containers:
    resources:
      cpu: 1200m
      memory: 2048Mi
    limits:
      cpu: 2000m
      memory: 4096Mi
    ports:
      containerPort: 9000
      name: sonarqube
    env:
      username: rrabanedo
      url: jdbc:postgresql:tcp://{{ tf_webservice_pip }}:5432/sonarqube
  initContainers:
    name: fix-the-volume-permission
    image: busybox
    volumeMounts:
      name: sonar
      mountPath: /opt/sonarqube

# The k8s Service yaml vars.
svc:
  name: sonarqube
  ports:
    name: sonar
    port: 1080
    protocol: TCP
    targetPort: 9000
  type: LoadBalancer

# The k8s PersistentVolumeClaim yaml vars.
pvc:
  name: sonar
  accessModes: ReadWriteOnce
  storageClassName: default
  storage: 5Gi

# k8s Secrets yaml info.
# Encrypted in Base64: echo -n '1nd3sc1fr4bl3@cp2' | base64
...