---
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
...