---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: latest

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
- name: Install python pre-requisites packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/tempfile_module.html
- name: Create kube directory for k8s' configuration file
  ansible.builtin.file:
    path: "{{ kube_config_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy config file in kube directory
  ansible.builtin.copy:
    src: "{{ kube_config_temp }}"
    dest: "{{ kube_config_path }}"
    mode: 0644

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/tempfile_module.html
- name: Create k8s temporary directory
  ansible.builtin.file:
    path: "{{ k8s_path }}"
    state: directory
  register: k8stemp

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
- name: Define PersistentVolumeClaim, secrets, deployment and services objects
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ k8s_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ k8s_templates }}"

# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
- name: Create a k8s namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ k8s_namespace }}"
    kubeconfig: "{{ kube_config_temp }}"

# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html
- name: Create a Deployment by reading the definition from a template
  kubernetes.core.k8s:
    state: present
    src: "{{ k8s_path }}/{{ item }}"
    kubeconfig: "{{ kube_config_temp }}"
  loop: "{{ k8s_templates }}"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Remove k8s temporary directory
  ansible.builtin.file:
    path: "{{ k8stemp.path }}"
    state: absent
  when: k8stemp.path is defined
...