---
# Playbook for provision the ansible.

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
# https://docs.ansible.com/ansible/latest/collections/community/general/ansible_galaxy_install_module.html
# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssh_keypair_module.html
- name: Install ansible-galaxy collection community.general
  hosts: 127.0.0.1
  gather_facts: true
  tasks:
    - name: Install ansible-galaxy collection community.general
      ansible.builtin.shell: "ansible-galaxy collection install community.general"
    - name: Install ansible community collections
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
        force: true
      loop:
        - community.crypto
        - containers.podman
        - community.postgresql
        - community.kubernetes
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        state: present
        force: no
...