---
# Playbook to install ansible-galaxy collection community.general for ansible.

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
- name: Install ansible-galaxy collection community.general
  hosts: 127.0.0.1
  gather_facts: true
  tasks:
    - name: Install ansible-galaxy collection community.general
      ansible.builtin.shell: "ansible-galaxy collection install community.general"
...