---
# Playbook for install the Webserver, SonarQube in Azure AKS and PostgreSQL like database.

# Install WS
- name: Install WS
  hosts: webservice
  vars_files:
    - global_vars/tf_ansible_vars.yml
  gather_facts: true
  become: true
  roles:
    - webservice
  tags:
    - webservice

# Install PostgreSQL
- name: Install PostgreSQL
  hosts: webservice
  vars_files:
    - global_vars/tf_ansible_vars.yml
  gather_facts: true
  become: true
  roles:
    - postgresql
  tags:
    - postgresql
    - k8s

# Install AKS (k8s SonarQube)
- name: Install AKS [k8s SonarQube]
  hosts: 127.0.0.1
  vars_files:
    - global_vars/tf_ansible_vars.yml
  gather_facts: true
  become: true
  roles:
    - sonarqube
  tags:
    - sonarqube
    - k8s
...