---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
- name: Install ansible community collections
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ ansible_collection }}"

# https://docs.ansible.com/ansible/latest/collections/community/general/ansible_galaxy_install_module.html
- name: Install ansible community.crypto
  community.general.ansible_galaxy_install:
    type: collection
    name: community.crypto
    force: true

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: yes
...