---
# vars file for webserver

# Packages necessary to install.
ws_packages:
  - httpd-tools
  - openssl
  - podman
  - skopeo
  - python3-passlib
  - python3-pyOpenSSL

# Username webservice access.
username: rabanedo
# Password webservice access.
password: 1qaz2wsx

# The algorithm used to generate the TLS/SSL private key.
key_type: RSA

# URL for ACR.
acr_url: rracontainerregistry.azurecr.io
# Username for ACR.
acr_username: rraContainerRegistry
# Password for ACR.
acr_password: "{{ tf_acr_password }}"
...